services:
  redbot:
    container_name: redbot
    image: phasecorex/red-discordbot:core
    restart: unless-stopped
    volumes:
      - ./redbot:/data
      - ./pcmasterrace:/cogs/pcmasterrace
      - ./hoyotools:/cogs/hoyotools
    env_file:
      - .env
    environment:
      EXTRA_ARGS: --dev --debug

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: "1450"
